name: Netlify
on:
  push:
    branches: main
    paths:
      - lambda/**
      - '!lambda/README.md'
      - netlify.toml
jobs:
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master # 这个action没有发布release（考虑换一个）
        with:
          args: deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
