name: Test
on:
  schedule:
    # CTAN上的包更新很频繁，但是没有相应的依赖管理机制，
    # 所以定期在主分支上运行单元测试以更新测试文件
    - cron: 0 0 * * 1 # 每周一零点
  push:
    paths-ignore:
      - 'lambda/**'
      - netlify.toml
  pull_request:
    branches: main

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        cache-version: [v20210607.1]
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Cache TeX Live
        if: github.event_name != 'schedule' # 定时测试不使用缓存
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: .ci-dock
          key: tl-${{ runner.os }}-${{ hashFiles('ci/texlive-packages') }}-${{ matrix.cache-version }}
      - name: Set up PATH
        shell: bash
        run: source ci/texlive-path.sh >> $GITHUB_PATH
      - name: Install TeX Live
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: source ci/texlive-install.sh
      - name: l3build
        run: l3build check -q
      - name: Check failure
        if: ${{ failure() }}
        shell: bash
        run: cat build/test/*.diff || cat build/test/*.fc
      - name: Doc
        run: l3build doc -q
